# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Model\EmailModel:
        $sendFromAddress: '%env(MAILER_SENDER_ADDRESS)%'

    Vinorcola\ApiServerTools\ExceptionSubscriber: ~
